version: 1.0.{build}

image: Visual Studio 2017

init:
  - cmd: git config --global core.autocrlf true

clone_folder: c:\mill

environment:
  matrix:
  - COMPILER: cygwin
    CYGWIN_DIR: cygwin64
    JAVA_HOME: C:\Program Files\Java\jdk9

cache:
  - '%LOCALAPPDATA%\Coursier\cache -> build.sc'

install:
  - SET MILL_URL=https://github.com/lihaoyi/mill/releases/download/0.1.7/0.1.7-97-00b10e

build_script:
  - if [%COMPILER%]==[cygwin] (
      SET "PATH=%JAVA_HOME%\bin;C:\%CYGWIN_DIR%\bin;C:\%CYGWIN_DIR%\usr\bin;%PATH%" &&
      C:\%CYGWIN_DIR%\bin\bash -lc 'mkdir -p /usr/local/bin' &&
      C:\%CYGWIN_DIR%\bin\bash -lc "curl -Lo /usr/local/bin/mill %MILL_URL%" &&
      C:\%CYGWIN_DIR%\bin\bash -lc 'sed -i '"'"'0,/-cp "\$0"/{s/-cp "\$0"/-cp `cygpath -w "\$0"`/}; 0,/-cp "\$0"/{s/-cp "\$0"/-cp `cygpath -w "\$0"`/}'"'"' /usr/local/bin/mill' &&
      C:\%CYGWIN_DIR%\bin\bash -lc 'chmod +x /usr/local/bin/mill' &&
      C:\%CYGWIN_DIR%\bin\bash -lc "cd /cygdrive/c/mill && mill -i main.test mill.main.ForeignBuildsTest")


skip_branch_with_pr: true
